In [1]:
import numpy as np

##Bubble Sort


*   A ordenação de dados passa por um passo preliminar para pesquisalos
*   o mais lento e o mais simples

*   Compara dois numeros, se o da esquerda for maior, os elementos são trocados, por vez diminuindo a quantidade de elementos comparados
   

*   N²/2 comparaçoes, há menos trocas que comparaçãoes
*   Item da lista






In [ ]:
def bubble_sort(vetor):
    n = len(vetor)

    for i in range(n):
        for j in range(0, n - i - 1):
            if vetor[j] > vetor [j + 1]:
              temp = vetor[j]
              vetor[j] = vetor [ j + 1]
              vetor[j + 1] = temp


    return vetor

In [ ]:
bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

##Selection Sort


*   Uma melhora de ordenação do Bubble sort, de N² para N
*   Vai pecorrer todos os elementos e selecionar o menor
*   Os elementos acumulam-se na esqueda
*   Permace com o mesmo número de comparações




In [2]:
def selection_sort(vetor):
    n = len(vetor)

    for i in range(n):
      id_minimo = 1
      for j in range( i + 1, n):
          if vetor[id_minimo] > vetor[j]:
            id_minimo =  j
      temp = vetor[i]
      vetor[i] = vetor[id_minimo]
      vetor[id_minimo] = temp

    return vetor

In [3]:
selection_sort(np.array([15, 34, 8, 3]))

array([ 3, 15,  8, 34])

##Insert Sort


*   Duas vezes mais rápido que o Bubble e Selection
*   Há um marcado no meio do vetor, os elementos da esqueda estão parcialmente ordenados e os da direita não estão ordernados


In [ ]:
def insertion_sort(vetor):
    n = len(vetor)

    for i in range (1, n):
        marcado = vetor[i]

        j = i - 1

        while j >= 0 and marcado < vetor[j]:
            vetor[ j + 1] = vetor[j]
            j -= 1
        vetor[j + 1] = marcado


    return vetor

In [ ]:
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

##Shell Sort
*  melhora a ordenação por inserção
*  vetor original é qiebrado em subvetores, cada subvetor é ordenando comparando e trocando os valores
*  Ao final de cada rodada, o subvetor é quebrado novamente ex: rod(1) = 10,  rod(2) = 5,  rod(3) = 2
*  Pior big-o  = O

In [ ]:
def shell_short(vetor):                           #vetor = [15, 34, 8, 3 , 1, 12]
    intervalo = len(vetor) // 2                   #trabalha somente com numeros inteiros

    while intervalo > 0:
        for i in range(intervalo, len(vetor)):    #Começa no inicio da divisão dos vetores(3)
            temp = vetor[i]                       #  i = 3 vetor[i] = vetor[3] = 3
            j = i                                 # j = i = 3
            while j >= intervalo and vetor[j - intervalo] > temp:
                                                  # j(3) >= inter(3) and [3 - 3 ] = [0 - inicial] > vetor[3] = 3
                vetor[j] = vetor[j - intervalo]   # vetor[3] = vetor[0]
                j -= intervalo                    # j = 0
            vetor[j] = temp                       # vetor[0] = vetor[3]

        intervalo //= 2                           # 3/2 = 1

    return vetor



In [ ]:
shell_short(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
shell_short(np.array([10, 8, 5, 6, 43, 2, 9]))

array([ 2,  5,  6,  8,  9, 10, 43])

##Merge Sort
*   Dividir em subproblemas(dividir e conquistar)
*   Divide o vetor continuamente pela metade, ordena e combina(renge)
*   Trabalha com recursão
*   Melhor e pior caso O(n*log n)

In [ ]:
def merge_sort(vetor):
  if len(vetor) > 1:
      divisao = len(vetor) // 2

      esquerda = vetor[:divisao].copy()
      direita = vetor[divisao:].copy()

      merge_sort(esquerda)
      merge_sort(direita)

      i = j = k = 0

      #ordenação esquerda e direita
      while i < len(esquerda) and j < len(direita):
          if esquerda[i]  < direita[i]:
              vetor[k] = esquerda[i]
              i += 1
          else:
              vetor[k] = direita[j]
              j += 1
          k += 1

      while i < len(esquerda):
          vetor[k] = esquerda[i]
          i += 1
          k += 1

      while j < len(direita):
          vetor[k] = direita[j]
          j += 1
          k += 1


  return vetor

In [ ]:
merge_sort(np.array([15, 32, 5, 8]))

array([ 5,  8, 15, 32])

##Quick Sort
*   

In [ ]:
def particao(vetor, inicio, final):
  pivo = vetor[final]
  i = inicio - 1

  for j in range(inicio, final):
    if vetor[j] <= pivo:
      i += 1
      vetor[i], vetor[j] = vetor[j], vetor[i]
  vetor[i + 1], vetor[final] = vetor[final], vetor[i + 1]
  return i + 1

def quick_sort(vetor, inicio, final):
  if inicio < final:
    posicao = particao(vetor, inicio, final)
    # Esquerda
    quick_sort(vetor, inicio, posicao - 1)
    # Direito
    quick_sort(vetor, posicao + 1, final)
  return vetor

In [ ]:
vetor = np.array([10, 8, 5, 6, 43, 2, 9])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 2,  5,  6,  8,  9, 10, 43])